xebialabs/xl-docker-images

xl-jetpack-deploy/8.6/amazonlinux/Dockerfile, xl-jetpack-deploy/8.6/centos/Dockerfile, xl-jetpack-deploy/8.6/debian-slim/Dockerfile
@ielshal there seems to be an issue with BYOL in the images. I have informed @hierynomus lets wait for his comment before merging and pushing the image.
=> Update XLD Jetpack images to include Terraform

applejack/conf/products/xl-deploy.yml, templates/resources/common/bin/db-drivers.sh, templates/resources/common/bin/run-in-container.sh.j2, templates/resources/xl-deploy/default-conf/xl-deploy.conf.template.j2
- Add necessary configuration to docker images to support xld task queue
=> DEPL-14939 Task Queue Implementation

applejack/conf/products/xl-deploy.yml, applejack/conf/products/xl-release.yml, templates/resources/common/bin/run-in-container.sh.j2
…f config files in case user wants to mount external config
=> DEPL-15223 Add environment variable to control automatic generation of config files in case user wants to mount external config

docs/environment-variables.md
=> Love 1341 - Document all available environment variables

docs/single-node-deployment.md
=> Love 1344 docs update

docs/customisation.md, documentation/customisation.md
=> LOVE-1343 Add some customisation documentation

docs/upgrade-single-node-deployment.md
=> LOVE-1345 - Document the upgrade for a single node deployment for XLD / XLR

.gitignore, docs/xl-deploy-ha/README.md, docs/xl-deploy-ha/docker-compose-xld-ha-workers.yaml, docs/xl-deploy-ha/docker-compose-xld-ha.yaml, docs/xl-deploy-ha/upgrade-multi-node-deployment.md, docs/xl-release-ha/README.md, docs/xl-release-ha/docker-compose-xlr-ha.yaml, docs/xl-release-ha/upgrade-multi-node-deployment.md
=> LOVE-1347 - Add Upgrade MultiNode docs

applejack/__init__.py
=> Update tag to replace + character with -

applejack/__init__.py
Reverts xebialabs/xl-docker-images#54
=> Revert "Update tag to replace + character with -"

applejack/__init__.py
Added Semantic Versioning for docker images as requested by bogdan.
=> Added Semantic Versioning for docker images

Jenkinsfile
=> ENG-2744 - Added workspace cleanup step after job execution

applejack/conf/products/xl-deploy.yml, templates/resources/xl-deploy/default-conf/xl-deploy.conf.template.j2
Raising PR to add support for satellites with XL Deploy.
The changes were tested locally.
=> Adding support for xl satellite

applejack/conf/products/xl-deploy.yml, templates/resources/xl-deploy/default-conf/xl-deploy.conf.template.j2
Raising PR to add support for XL satellite with XL Deploy
Changes were tested locally before raising the PR
=> Added support for xl satellite

templates/dockerfiles/debian-slim/Dockerfile.j2, xl-deploy/10.0/debian-slim/Dockerfile, xl-deploy/9.7/debian-slim/Dockerfile
=> ENG-1643 Added missing packages in openjdk slim

templates/resources/central-configuration/help.md.j2
=> ENG-7300 Add help doc steps about ssl settings in cc docker image

documentation/docs/manual/xl-deploy-ha/xl-deploy-master/conf/logback.xml, documentation/docs/manual/xl-deploy-ha/xl-deploy-worker/conf/logback.xml, templates/resources/deploy-task-engine/default-conf/logback.xml, templates/resources/xl-deploy/central-conf/logback.xml, templates/resources/xl-deploy/default-conf/logback.xml
=> ENG-8185 add ai.digital logger conf

applejack/conf/products/central-configuration.yml, applejack/conf/products/xl-deploy.yml, templates/dockerfiles/central-configuration/install.j2, templates/resources/central-configuration/central-conf/boot.conf.template.j2, templates/resources/common/default-conf/boot.conf.cloud.template.j2, templates/resources/includes/central-configuration-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> ENG-7206 -  Added changes related to spring.cloud.encrypt.key

applejack/conf/products/deploy-task-engine.yml
=> Add plugin-source to task-engine env

templates/resources/common/bin/run-in-container.sh.j2
=> ENG-8508 - added check for   not to override existing cc yaml

applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml, templates/resources/common/bin/run-in-container.sh.j2, templates/resources/deploy-task-engine/bin/run-in-container.sh.j2
=> ENG-8798 Use derby as default db for deploy

applejack/conf/products/xl-release.yml, templates/resources/common/bin/run-in-container.sh.j2
https://digitalai.atlassian.net/browse/ENG-8675
**General**
=> ENG-8675 Add to the xl-release docker image support for the option -force-remove-missing-types

templates/resources/common/bin/run-in-container.sh.j2, templates/resources/deploy-task-engine/bin/run-in-container.sh.j2
https://digitalai.atlassian.net/browse/ENG-8876
**General**
=> ENG_8876 Disable PLUGIN_SOURCE env variable for XLD and XLR < 22.0.0

templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> ENG-8415 - changes for to consider central config url while upgrade #115

templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
Reverts xebialabs/xl-docker-images#116
=> Revert "ENG-8415 - changes for to consider central config url while upgrade #115"

templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
Reverts xebialabs/xl-docker-images#117
=> Revert "ENG-8415 - changes for consider central config url while upgrading from older than 10.3"

templates/resources/common/default-conf/boot.conf.cloud.template.j2, templates/resources/common/default-conf/boot.conf.template.j2, templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> ENG-8098 - docker changes

templates/resources/common/default-conf/boot.conf.cloud.template.j2, templates/resources/common/default-conf/boot.conf.template.j2, templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> ENG-8098 -22.0.x docker changes

templates/resources/common/bin/run-in-container.sh.j2
https://digitalai.atlassian.net/browse/FI-979
**General**
=> FI-979 operator upgrade Issue || Clean up missing types

applejack/conf/products/xl-release.yml, templates/resources/common/bin/run-in-container.sh.j2
https://digitalai.atlassian.net/browse/FI-979
**General**
=> [10.3] FI-979 operator upgrade Issue || Clean up missing types

templates/resources/common/bin/run-in-container.sh.j2
https://digitalai.atlassian.net/browse/FI-979
**General**
=> [22.0] FI-979 operator upgrade Issue || Clean up missing types

templates/resources/common/default-conf/boot.conf.cloud.template.j2, templates/resources/common/default-conf/boot.conf.template.j2, templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> ENG-8916 10.3.x xl-docker-images

applejack/conf/products/xl-release.yml, templates/resources/xl-release/default-conf/xl-release.conf.template.j2
=> S-91791 Add XLR configuration to define max-number of connections for external DBs

applejack/conf/products/xl-release.yml, templates/resources/includes/xl-release-run-script.j2
=> D-24449 Displaying correct port with default configuration during release startup

documentation/docs/manual/xl-client-docker-run.md, templates/dockerfiles/xl-cli/Dockerfile.j2
=> S 91946 23.1 - Added xl-cli dependencies for aws, and gcp

documentation/docs/manual/xl-client-docker-run.md, templates/dockerfiles/xl-cli/Dockerfile.j2
=> S-91946- master Added xl-cli dependencies for aws, and gcp

templates/resources/includes/xl-release-run-script.j2
=> S-90616 [23.1] Fixed typo in xl release server config 

templates/resources/includes/xl-release-run-script.j2
=> S-90616 Fixed typo in xl release server config

documentation/docs/manual/ECS-installation.md, templates/dockerfiles/runtime.j2
…WS EFS volumes to the container using 'xebialabs' user
**General**
=> D-24195- XLR - DAI Upgrade issue - Getting error when attaching new AWS EFS volumes to the container using 'xebialabs' user

templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> S-92636 Fix problem with missing new line on the end of file

.gitignore, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
=> S-92340 Upgrade gradle version upgrade to 8.1.1

build.gradle.kts, templates/dockerfiles/amazonlinux/Dockerfile.j2, templates/dockerfiles/centos/Dockerfile.j2, templates/dockerfiles/debian-slim/Dockerfile.j2, templates/dockerfiles/rhel/Dockerfile.j2, templates/dockerfiles/xl-cli/Dockerfile.j2
=> S-94173 - jdk17 upgrade

templates/resources/includes/deploy-task-engine-run-script.j2, templates/resources/includes/xl-deploy-run-script.j2
=> S-92295 Support upgrade with new properties mappings

applejack/conf/products/central-configuration.yml, applejack/conf/products/xl-deploy.yml
=> D-26828 fix report db default env for central configuration and xl-deploy

applejack/conf/products/central-configuration.yml, applejack/conf/products/xl-deploy.yml
=> D-26828 fix report db default env for central configuration and xl-deploy (#198)

Jenkinsfile, applejack/conf/products/central-configuration.yml, applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml, applejack/conf/products/xl-release.yml, copy_docker_images.sh, documentation/docs/building.md, templates/dockerfiles/ubuntu/Dockerfile.j2
=> adding ubuntu image support.

applejack/conf/products/central-configuration.yml, applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml, applejack/conf/products/xl-release.yml
=> changing ubuntu as default image

templates/resources/xl-release/default-conf/logback.xml, templates/resources/xl-release/default-conf/xl-release.conf.template.j2
=> S-97337 Akka2Pekko migration

applejack/conf/products/central-configuration.yml, applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml, applejack/conf/products/xl-release.yml, templates/resources/central-configuration/central-conf/logback.xml, templates/resources/deploy-task-engine/default-conf/logback.xml, templates/resources/xl-deploy/central-conf/logback.xml, templates/resources/xl-deploy/default-conf/logback.xml, templates/resources/xl-release/default-conf/logback.xml
=> S-85794 - Better container logging configuration for scan and logging level

templates/resources/common/bin/db-drivers.sh
=> S-104353 Fix vulnerabilities

templates/dockerfiles/central-configuration/install.j2, templates/dockerfiles/deploy-task-engine/install.j2, templates/dockerfiles/install.j2, templates/dockerfiles/runtime.j2
=> S-104302 use non-root user and group for docker app containers

applejack/conf/products/xl-client.yml, templates/dockerfiles/xl-cli/Dockerfile.j2
=> S-96287 Detached installation of the Release and RRR

templates/dockerfiles/xl-cli/Dockerfile.j2
=>  S-107523 xl-cli deps bump

applejack/conf/products/xl-release.yml, templates/resources/xl-release/default-conf/xl-release.conf.template.j2
=> S-108057 Support rabbitmq quorum queue for Release

applejack/conf/products/central-configuration.yml, applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml, templates/resources/deploy-central-configuration/central-conf/deploy-task.yaml.template.j2
=> S-97235 Support rabbitmq quorum queue for deploy

applejack/conf/products/xl-release.yml, templates/resources/common/bin/db-drivers.sh, templates/resources/xl-release/default-conf/xl-release.conf.template.j2
=> S-108057 Fix - connection issues with quorum queue in rabbitmq

templates/resources/includes/central-configuration-run-script.j2
=> D-34407 type-default.properties are not synced from the central-conf

templates/dockerfiles/central-configuration/install.j2, templates/dockerfiles/deploy-task-engine/install.j2, templates/dockerfiles/install.j2, templates/dockerfiles/runtime.j2, templates/resources/includes/central-configuration-run-script.j2
=> S-109086 installation without root user

templates/dockerfiles/install.j2
=> S-111219 Remove service wrapper and related files

documentation/docs/manual/xl-deploy-ha/xl-deploy-master/centralConfiguration/deploy-oidc.yaml
=> Added two new claims for email and fullname in oidc configuration

templates/dockerfiles/install.j2
Remove service wrapper and related files when build using this branch. No change done to effect skip_vulnerable_libs flag.
**General**
=> S-111925 : 23.3 : Remove service wrapper and related files

templates/dockerfiles/centos/Dockerfile.j2
Updating centos base image
**General**
=> S-112522 Update Dockerfile.j2

templates/dockerfiles/centos/Dockerfile.j2
=> Centos image update with ssl issue fixed

documentation/docs/manual/xl-deploy-ha/xl-deploy-master/centralConfiguration/deploy-oidc.yaml
=> S-112752 - Fullname and Email oidc config name to sync with release

templates/resources/central-configuration/central-conf/logback.xml
=> D-36919 remove logback logging in file for cc

applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml
=> D-36954 24.1 branch: Dropping trial-edition and switching to server

applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml
=> D-36954 23.3 branch: Dropping trial-edition and switching to server

applejack/conf/products/deploy-task-engine.yml, applejack/conf/products/xl-deploy.yml
=> D-36954 master branch: Dropping server-trial-edition.zip and switching to server.zip

templates/resources/common/bin/drivers.sh.j2
=> S-113491 CVE - upgrade db connector jar versions

templates/resources/common/bin/drivers.sh.j2
=> [24.1] S-113491 CVE - upgrade db connector jar versions

applejack/conf/products/xl-deploy.yml, applejack/conf/products/xl-release.yml, documentation/docs/manual/environment-variables.md, templates/resources/common/default-conf/security.properties.template.j2, templates/resources/includes/xl-deploy-run-script.j2, templates/resources/includes/xl-release-run-script.j2
=> S-116580 add security.properties file to docker conf templates

applejack/conf/products/xl-release.yml, documentation/docs/manual/environment-variables.md, templates/resources/common/bin/run-in-container.sh.j2, templates/resources/xl-release/default-conf/xl-release.conf.template.j2, templates/resources/xl-release/node-conf/xl-release.conf.template.j2
=> S-117058 multi-dc support conf

templates/dockerfiles/install.j2
=> D-39435 Update jmx_prometheus_javaagent jar

applejack/conf/products/deploy-task-engine.yml, templates/resources/includes/deploy-task-engine-run-script.j2
=> S-116709 Add JVM networkaddress.cache.ttl to deploy task engine

templates/resources/common/bin/run-in-container.sh.j2, templates/resources/deploy-task-engine/bin/run-in-container.sh.j2
=> D-39562 fix mysql driver and env parsing

applejack/__init__.py
=> S-120924 Additional major.minor.patch tagging for images

applejack/__init__.py
=> S-120924 [24.3] Additional major.minor.patch tagging for images
